/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     2017/6/8 11:17:10                            */
/*==============================================================*/


drop table if exists biz_order_install_item_report;

/*==============================================================*/
/* Table: biz_order_install_item_report                         */
/*==============================================================*/
create table biz_order_install_item_report
(
   id                             int(11)         not null auto_increment comment 'id -- \'',
   engin_depart_id                int(11)         comment '工程部id -- \'',
   order_id                       int(11)         comment '订单id -- \'',
   order_number                   varchar(100)    comment '订单编号 -- \'',
   customer_name                  varchar(20)     comment '客户姓名 -- \'',
   customer_phone                 varchar(11)     comment '客户手机号 -- \'',
   pm_name                        varchar(20)     comment '项目经理姓名 -- \'',
   actual_start_date              date            comment '实际开工日期 -- \'',
   checksize_apply_datetime_chugui datetime        comment '申报核尺日期时间_橱柜 -- \'',
   install_item_apply_datetime_chugui datetime        comment '安装提报日期时间_橱柜 -- \'',
   install_item_apply_into_date_chugui date            comment '期望进场日期_橱柜 -- \'',
   install_item_real_into_date_chugui date            comment '实际进场日期_橱柜 -- \'',
   install_item_real_accept_date_chugui date            comment '实际验收日期_橱柜 -- \'',
   install_item_is_returned_chugui varchar(1)      comment '是否返工_橱柜 -- \'0.否；1.是；',
   install_item_problem_describe_chugui varchar(225)    comment '安装问题描述_橱柜 -- \'',
   install_item_problem_apply_datetime_chugui datetime        comment '安装问题提交日期时间_橱柜 -- \'',
   install_item_problem_solve_datetime_chugui datetime        comment '解决完成日期时间_橱柜 -- \'',
   spend_time_chugui              decimal(8,2)    comment '总共用时_橱柜 -- \'',
   checksize_apply_datetime_fangmen datetime        comment '申报核尺日期时间_房门 -- \'',
   install_item_apply_datetime_fangmen datetime        comment '安装提报日期时间_房门 -- \'',
   install_item_apply_into_date_fangmen date            comment '期望进场日期_房门 -- \'',
   install_item_real_into_date_fangmen date            comment '实际进场日期_房门 -- \'',
   install_item_real_accept_date_fangmen date            comment '实际验收日期 -- \'',
   install_item_is_returned_fangmen varchar(1)      comment '是否返工_房门 -- \'0.否；1.是；',
   install_item_problem_describe_fangmen varchar(225)    comment '安装问题描述_房门 -- \'',
   install_item_problem_apply_datetime_fangmen datetime        comment '安装问题提交日期时间_房门 -- \'',
   install_item_problem_solve_datetime_fangmen datetime        comment '解决完成日期时间_房门 -- \'',
   spend_time_fangmen             decimal(8,2)    comment '总共用时_房门 -- \'',
   checksize_apply_datetime_jieju datetime        comment '申报核尺日期时间_洁具 -- \'',
   install_item_apply_datetime_jieju datetime        comment '安装提报日期时间_洁具 -- \'',
   install_item_apply_into_date_jieju date            comment '期望进场日期_洁具 -- \'',
   install_item_real_into_date_jieju date            comment '实际进场日期_洁具 -- \'',
   install_item_real_accept_date_jieju date            comment '实际验收日期_洁具 -- \'',
   install_item_is_returned_jieju varchar(1)      comment '是否返工_洁具 -- \'0.否；1.是；',
   install_item_problem_describe_jieju varchar(225)    comment '安装问题描述_洁具 -- \'',
   install_item_problem_apply_datetime_jieju datetime        comment '安装问题提交日期时间_洁具 -- \'',
   install_item_problem_solve_datetime_jieju datetime        comment '解决完成日期时间_洁具 -- \'',
   spend_time_jieju               decimal(8,2)    comment '总共用时_洁具 -- \'',
   checksize_apply_datetime_bizhi datetime        comment '申报核尺日期时间_壁纸 -- \'',
   install_item_apply_datetime_bizhi datetime        comment '安装提报日期时间_壁纸 -- \'',
   install_item_apply_into_date_bizhi date            comment '期望进场日期_壁纸 -- \'',
   install_item_real_into_date_bizhi date            comment '实际进场日期_壁纸 -- \'',
   install_item_real_complete_date_bizhi date            comment '实际验收日期_壁纸 -- \'',
   install_item_is_returned_bizhi varchar(1)      comment '是否返工_壁纸 -- \'0.否；1.是；',
   install_item_problem_describe_bizhi varchar(225)    comment '安装问题描述_壁纸 -- \'',
   install_item_problem_apply_datetime_bizhi datetime        comment '安装问题提交日期时间_壁纸 -- \'',
   install_item_problem_solve_datetime_bizhi datetime        comment '解决完成日期时间_壁纸 -- \'',
   spend_time_bizhi               decimal(8,2)    comment '总共用时_壁纸 -- \'',
   checksize_apply_datetime_mudiban datetime        comment '申报核尺日期时间_木地板 -- \'',
   install_item_apply_datetime_mudiban datetime        comment '安装提报日期时间_木地板 -- \'',
   install_item_apply_into_date_mudiban date            comment '期望进场日期_木地板 -- \'',
   install_item_real_into_date_mudiban date            comment '实际进场日期_木地板 -- \'',
   install_item_real_accept_date_mudiban date            comment '实际验收日期_木地板 -- \'',
   install_item_is_returned_mudiban varchar(1)      comment '是否返工_木地板 -- \'0.否；1.是；',
   install_item_problem_describe_mudiban varchar(225)    comment '安装问题描述_木地板 -- \'',
   install_item_problem_apply_datetime_mudiban datetime        comment '安装问题提交日期时间_木地板 -- \'',
   install_item_problem_solve_datetime_mudiban datetime        comment '解决完成日期时间_木地板 -- \'',
   spend_time_mudiban             decimal(8,2)    comment '总共用时_木地板 -- \'',
   checksize_apply_datetime_diaoding datetime        comment '申报核尺日期时间_吊顶 -- \'',
   install_item_apply_datetime_diaoding datetime        comment '安装提报日期时间_吊顶 -- \'',
   install_item_apply_into_date_diaoding date            comment '期望进场日期_吊顶 -- \'',
   install_item_real_into_date_diaoding date            comment '实际进场日期_吊顶 -- \'',
   install_item_real_accept_date_diaoding date            comment '实际验收日期_吊顶 -- \'',
   install_item_is_returned_diaoding varchar(1)      comment '是否返工_吊顶 -- \'0.否；1.是；',
   install_item_problem_describe_diaoding varchar(225)    comment '安装问题描述_吊顶 -- \'',
   install_item_problem_apply_datetime_diaoding datetime        comment '安装问题提交日期时间_吊顶 -- \'',
   install_item_problem_solve_datetime_diaoding datetime        comment '解决完成日期时间_吊顶 -- \'',
   spend_time_diaoding            decimal(8,2)    comment '总共用时_吊顶 -- \'',
   checksize_apply_datetime_dengju datetime        comment '申报核尺日期时间_灯具 -- \'',
   install_item_apply_datetime_dengju datetime        comment '安装提报日期时间_灯具 -- \'',
   install_item_apply_into_date_dengju date            comment '期望进场日期_灯具 -- \'',
   install_item_real_into_date_dengju date            comment '实际进场日期_灯具 -- \'',
   install_item_real_accept_date_dengju date            comment '实际验收日期_灯具 -- \'',
   install_item_is_returned_dengju varchar(1)      comment '是否返工_灯具 -- \'0.否；1.是；',
   install_item_problem_describe_dengju varchar(225)    comment '安装问题描述_灯具 -- \'',
   install_item_problem_apply_datetime_dengju datetime        comment '安装问题提交日期时间_灯具 -- \'',
   install_item_problem_solve_datetime_dengju datetime        comment '解决完成日期时间_灯具 -- \'',
   spend_time_dengju              decimal(8,2)    comment '总共用时_灯具 -- \'',
   checksize_apply_datetime_chuanglian datetime        comment '申报核尺日期时间_窗帘 -- \'',
   install_item_apply_datetime_chuanglian datetime        comment '安装提报日期时间_窗帘 -- \'',
   install_item_apply_into_date_chuanglian date            comment '期望进场日期_窗帘 -- \'',
   install_item_real_into_date_chuanglian date            comment '实际进场日期_窗帘 -- \'',
   install_item_real_accept_date_chuanglian date            comment '实际验收日期_窗帘 -- \'',
   install_item_is_returned_chuanglian varchar(1)      comment '是否返工_窗帘 -- \'0.否；1.是；',
   install_item_problem_describe_chuanglian varchar(225)    comment '安装问题描述_窗帘 -- \'',
   install_item_problem_apply_datetime_chuanglian datetime        comment '安装问题提交日期时间_窗帘 -- \'',
   install_item_problem_solve_datetime_chuanglian datetime        comment '解决完成日期时间_窗帘 -- \'',
   spend_time_chuanglian          decimal(8,2)    comment '总共用时_窗帘 -- \'',
   checksize_apply_datetime_linyufang datetime        comment '申报核尺日期时间_淋浴房 -- \'',
   install_item_apply_datetime_linyufang datetime        comment '安装提报日期时间_淋浴房 -- \'',
   install_item_apply_into_date_linyufang date            comment '期望进场日期_淋浴房 -- \'',
   install_item_real_into_date_linyufang date            comment '实际进场日期_淋浴房 -- \'',
   install_item_real_accept_date_linyufang date            comment '实际验收日期_淋浴房 -- \'',
   install_item_is_returned_linyufang varchar(1)      comment '是否返工_淋浴房 -- \'0.否；1.是；',
   install_item_problem_describe_linyufang varchar(225)    comment '安装问题描述_淋浴房 -- \'',
   install_item_problem_apply_datetime_linyufang datetime        comment '安装问题提交日期时间_淋浴房 -- \'',
   install_item_problem_solve_datetime_linyufang datetime        comment '解决完成日期时间_淋浴房 -- \'',
   spend_time_linyufang           decimal(8,2)    comment '总共用时_淋浴房 -- \'',
   checksize_apply_datetime_yigui datetime        comment '申报核尺日期时间_定制衣柜 -- \'',
   install_item_apply_datetime_yigui datetime        comment '安装提报日期时间_定制衣柜 -- \'',
   install_item_apply_into_date_yigui date            comment '期望进场日期_定制衣柜 -- \'',
   install_item_real_into_date_yigui date            comment '实际进场日期_定制衣柜 -- \'',
   install_item_real_accept_date_yigui date            comment '实际验收日期_定制衣柜 -- \'',
   install_item_is_returned_yigui varchar(1)      comment '是否返工_定制衣柜 -- \'0.否；1.是；',
   install_item_problem_describe_yigui varchar(225)    comment '安装问题描述_定制衣柜 -- \'',
   install_item_problem_apply_datetime_yigui datetime        comment '安装问题提交日期时间_定制衣柜 -- \'',
   install_item_problem_solve_datetime_yigui datetime        comment '解决完成日期时间_定制衣柜 -- \'',
   spend_time_yigui               decimal(8,2)    comment '总共用时_定制衣柜 -- \'',
   primary key (id)
);

