INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('9','2','1','','提出面板灯具安装验收申请','0','面板灯具工程','1','手动','','6','100','7','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');

INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('10','818','1','','提出水电验收申请','0','水电隐蔽工程','1','手动','','1','100','53','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('11','818','1','','提出闭水实验和隐蔽工程验收申请','0','防水工程','1','手动','','2','100','54','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('12','818','1','','提出瓦工墙地砖验收申请','0','泥工/木工工程','1','手动','','3','100','55','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('13','818','1','','二期款催缴','0','油工工程','1','手动','','4','200',null,null,null,'2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('14','818','1','','提出涂饰工程及基装验收申请','0','油工工程','1','手动','','5','100','56','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('15','818','1','','提出面板灯具安装验收申请','0','面板灯具工程','1','手动','','6','100','57','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('16','818','1','','提出竣工验收申请','0','竣工验收','1','手动','','6','100','58','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('17','3','1','','提出水电验收申请','0','水电隐蔽工程','1','手动','','1','100','10','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('18','3','1','','提出闭水实验和隐蔽工程验收申请','0','防水工程','1','手动','','2','100','11','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('19','3','1','','提出瓦工墙地砖验收申请','0','泥工/木工工程','1','手动','','3','100','12','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('20','3','1','','二期款催缴','0','油工工程','1','手动','','4','200',null,null,null,'2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('21','3','1','','提出涂饰工程及基装验收申请','0','油工工程','1','手动','','5','100','15','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('22','3','1','','提出面板灯具安装验收申请','0','面板灯具工程','1','手动','','6','100','16','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('23','3','1','','提出竣工验收申请','0','竣工验收','1','手动','','7','100','18','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('24','816','1','','提出闭水实验和隐蔽工程验收申请','0','水电隐蔽工程','1','手动','','1','100','29','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('25','816','1','','提出闭水实验和隐蔽工程验收申请','0','防水工程','1','手动','','2','100','30','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('26','816','1','','提出瓦工墙地砖验收申请','0','泥工/木工工程','1','手动','','3','100','31','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('27','816','1','','二期款催缴','0','油工工程','1','手动','','4','200',null,null,null,'2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('28','816','1','','提出涂饰工程及基装验收申请','0','油工工程','1','手动','','5','100','34','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('29','816','1','','面板灯具安装验收','0','面板灯具工程','1','手动','','6','100','35','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('30','816','1','','提出竣工验收申请','0','竣工验收','1','手动','','7','100','37','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('31','817','1','','提出水电验收申请','0','水电隐蔽工程','1','手动','','1','100','43','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('32','817','1','','提出闭水实验和隐蔽工程验收申请','0','防水工程','1','手动','','2','100','44','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('33','817','1','','提出瓦工墙地砖验收申请','0','泥工/木工工程','1','手动','','3','100','45','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('34','817','1','','二期款催缴','0','油工工程','1','手动','','4','200',null,null,null,'2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('35','817','1','','提出涂饰工程及基装验收申请','0','油工工程','1','手动','','5','100','46','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('36','817','1','','提出面板灯具安装验收','0','面板灯具工程','1','手动','','6','100','49','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
INSERT INTO `biz_todo_item_type` (`id`, `store_id`, `project_mode`, `todo_item_code`, `todo_item_name`, `days_to_remind`, `business_step`, `is_to_remind`, `todo_item_generate_style`, `todo_item_remarks`, `sort_index`, `related_business_type`, `related_business_id`, `remarks`, `create_by`, `create_date`, `update_by`, `update_date`, `del_flag`) VALUES
 ('37','817','1','','提出竣工验收申请','0','竣工验收','1','手动','','7','100','48','','','2017/7/27  12:00:00','1','2017/7/27  12:00:00','0');
