<%@ page contentType="text/html;charset=UTF-8" %>
<%@ include file="/WEB-INF/views/include/taglib.jsp"%>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>进度大看板取值说明</title>
	<!-- <link rel="stylesheet" href="css/base.css">
	<link rel="stylesheet" href="css/index.css">
	<link rel="stylesheet" href="${ctxStatic}/modules/projectProgress/css/base.css">
	<link rel="stylesheet" href="${ctxStatic}/modules/projectProgress/css/index.css">-->
	<link rel="stylesheet" href="${ctxStatic}/modules/projectProgress/css/layout.css">
</head>
<body>
<div class="wrap">
	<table>
		<caption>进度看板取值说明</caption>
		<thead>
		<tr>
			<th colspan="2">列标题</th>
			<th class="w50">标识</th>
			<th>取值说明</th>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td colspan="2">门店</td>
			<td></td>
			<td>项目经理所属门店名称</td>
		</tr>
		<tr>
			<td colspan="2">区域</td>
			<td></td>
			<td>项目经理所属大区名称</td>
		</tr>
		<tr>
			<td colspan="2">项目编号</td>
			<td></td>
			<td>订单表订单编号</td>
		</tr>
		<tr>
			<td colspan="2">片区</td>
			<td></td>
			<td>biz_order表中片区</td>
		</tr>
		<tr>
			<td colspan="2">接单日期</td>
			<td></td>
			<td>订单表的get_order_datetime</td>
		</tr>
		<tr>
			<td colspan="2">客户姓名</td>
			<td></td>
			<td>订单表客户姓名</td>
		</tr>
		<tr>
			<td colspan="2">客户电话</td>
			<td></td>
			<td>订单表客户电话</td>
		</tr>
		<tr>
			<td colspan="2">工程地址</td>
			<td></td>
			<td>小区名称-楼号-单元号-门牌号</td>
		</tr>
		<tr>
			<td colspan="2">合同面积</td>
			<td></td>
			<td>biz_order表中contract_area</td>
		</tr>
		<tr>
			<td colspan="2">房屋类型</td>
			<td></td>
			<td>biz_order表中build_type</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="2" class="line_60 w150">项目经理</td>
			<td class="w150">姓名</td>
			<td></td>
			<td>项目经理姓名</td>
		</tr>
		<tr>
			<td>电话</td>
			<td></td>
			<td>项目经理电话</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="2">设计师</td>
			<td>姓名</td>
			<td></td>
			<td>设计师姓名</td>
		</tr>
		<tr>
			<td>电话</td>
			<td></td>
			<td>设计师电话</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="2" class="line_60 w150">质检员</td>
			<td class="w150">姓名</td>
			<td></td>
			<td>质检员姓名</td>
		</tr>
		<tr>
			<td>电话</td>
			<td></td>
			<td>质检员电话</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="2">合同工期时间</td>
			<td>合同签订开工</td>
			<td>A</td>
			<td>订单表合同开工日期contract_start_date</td>
		</tr>
		<tr>
			<td>合同签订竣工</td>
			<td>B</td>
			<td>订单表合同开工日期contract_end_date</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="2">实际工期时间</td>
			<td>实际开工时间</td>
			<td>C</td>
			<td>订单表合同开工日期actual_start_date</td>
		</tr>
		<tr>
			<td>竣工日期</td>
			<td>D</td>
			<td>订单表合同开工日期actual_end_date</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td colspan="2">开工延期天数</td>
			<td>E</td>
			<td>C-A</td>
		</tr>
		<tr>
			<td colspan="2">客户认可延期天数</td>
			<td>F</td>
			<td>延期单中审核通过的延期总天数</td>
		</tr>
		<tr>
			<td colspan="2">实际开工客户是否签字</td>
			<td>G</td>
			<td>实际开工表biz_order_confirm_startwork的is_need_sign</td>
		</tr>
		<tr>
			<td colspan="2">变更/停电/停水/客户自装项目延期天数</td>
			<td>H</td>
			<td>订单表延期类型delay_type</td>
		</tr>
		<tr>
			<td colspan="2">客户是否签字</td>
			<td></td>
			<td>确认开工的【开工客户签字】</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">防盗门核尺<i>(第3天)</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>取确认开工时间</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>项目经理提交的第一个申请厂家复尺单且【复尺类型是防盗门】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>项目经理第一次申请防盗门复尺复尺类型是【防盗门】的【期望复尺时间】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td></td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>项目经理提交的第一个申请厂家复尺单且【复尺类型是防盗门】的【供应商确认时间】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="9">辅材进场<i>(3天内)</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>G-3</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>项目经理申请第一单辅料单的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>项目经理申请第一单辅料单的【期望进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td></td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际收货时间</td>
			<td>H</td>
			<td>项目经理提交的第一个【收货类型=辅料】的收货单的【实际送货日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">瓷砖<i>（第3天通知，厂家第8天送到）</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>G-3</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>项目经理申请第一单辅料单的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>项目经理申请第一单辅料单的【期望进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td></td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际收货时间</td>
			<td>H</td>
			<td>项目经理提交的第一个【收货类型=墙地砖】的收货单的【实际送货日期】项目经理提交的第一个【收货类型=墙地砖】的收货单的【实际送货日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="9">水电隐蔽验收<i>（第10天）</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>G-3</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望验收日期</td>
			<td>D</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【期望上门日期】</td>
		</tr>
		<tr>
			<td>质检上门日期</td>
			<td>E</td>
			<td>质检员签到查询表中的【签到日期】</td>
		</tr>
		<tr>
			<td>上门延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划验收日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际验收合格日期</td>
			<td>H</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认】且【节点是水电隐蔽验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">防水验收<i>（18天）</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>G-3</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认】且【节点是防水验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望验收日期</td>
			<td>D</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【期望上门日期】</td>
		</tr>
		<tr>
			<td>质检上门日期</td>
			<td>E</td>
			<td>质检员签到查询表中的【签到日期】</td>
		</tr>
		<tr>
			<td>上门延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划验收日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际验收合格日期</td>
			<td>H</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认】且【节点是防水验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="9">橱柜核尺<i>（第20天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（橱柜、台面）中实际开工后第几天申请</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>项目经理提交的第一个申请厂家复尺单且【复尺类型是橱柜】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>项目经理提报橱柜核尺的【期望进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td></td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>项目经理提交的第一个申请厂家复尺单且【复尺类型是橱柜】的【复尺日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">瓦工验收<i>（第32天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+约检节点（瓦工验收）中的开工后第几天申请</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【期望上门日期】</td>
		</tr>
		<tr>
			<td>质检上门日期</td>
			<td>E</td>
			<td>质检员（瓦工验收节点）签到时间</td>
		</tr>
		<tr>
			<td>上门延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划验收日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际验收合格日期</td>
			<td>H</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认】且【节点是瓦工验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="4">二期款<i>（同瓦工验收日期）</i></td>
			<td>计划</td>
			<td>A</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>催款</td>
			<td>B</td>
			<td>项目经理提交的第一个催缴二期款单据的日期但，暂无此功能所以取，biz_qc_bill【约检单】且【状态是已质检确认】且【节点是瓦工验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>实际</td>
			<td>C</td>
			<td>客户实际收交二期款的日期，数据来源biz_pre_pm_settle_finance_receive_moeny表中receive_money_type为1的交款时间receive_money_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>D</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">基础施工验收<i>（第40天）</i></td>
			<td>计划提报日期</td>
			<td>A</td>
			<td>实际开工日期+约检节点（基础施工验收）中的开工后第几天申请</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望验收日期</td>
			<td>D</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是水电隐蔽验收】的【期望上门日期】</td>
		</tr>
		<tr>
			<td>质检上门日期</td>
			<td>E</td>
			<td>约检（基装验收节点）签到时间</td>
		</tr>
		<tr>
			<td>上门延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划验收日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际验收合格日期</td>
			<td>H</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认（状态值 >=10，只要质检通过即可）】且【节点是基装验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="10">厨卫吊顶<i>(第37天)</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（铝扣板安装）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是铝扣板安装】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是铝扣板安装】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是铝扣板安装】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是铝扣板安装】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是铝扣板安装】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="10">洁具<i>（第38天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（洁具安装）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是洁具】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是洁具】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是洁具】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是洁具】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是洁具】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="10">五金，灯具，开关面板<i>（第44天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（灯具开关小五金）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是灯具】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是灯具】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是灯具】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是灯具】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是灯具】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>H-G</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="11">橱柜<i>（第46天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（橱柜、台面）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是橱柜】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>提报核尺时间 </td>
			<td>D</td>
			<td>项目经理提报复尺单，类别为【橱柜】的【创建时间】</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是橱柜】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>F</td>
			<td>biz_order_install_plan中【安装项是橱柜】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>G</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>H</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是橱柜】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>J</td>
			<td>biz_order_install_plan中【安装项是橱柜】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>K</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="11">定制衣柜<i>（同橱柜安装日期）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（定制柜）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是定制衣柜】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>核尺时间 </td>
			<td>D</td>
			<td>项目经理提报复尺单，类别为【定制衣柜】的【创建时间】</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是定制衣柜】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>F</td>
			<td>biz_order_install_plan中【安装项是定制衣柜】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>G</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>H</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是定制衣柜】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>J</td>
			<td>biz_order_install_plan中【安装项是定制衣柜】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>K</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="10">壁纸<i>（第48天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（壁纸安装）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是壁纸】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是壁纸】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是壁纸】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是壁纸】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是壁纸】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="11">木门，铝镁门，门窗套<i>（第49天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（内门）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是木门】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>核尺时间 </td>
			<td>D</td>
			<td>项目经理提交申请核尺单，类别为【木门，铝镁门，门窗套】的【创建时间】</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是木门】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>F</td>
			<td>biz_order_install_plan中【安装项是木门】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>G</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>H</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是木门】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>J</td>
			<td>biz_order_install_plan中【安装项是木门】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>K</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="10">木地板<i>（第51天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（木地板安装）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是木地板】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是木地板】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是木地板】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是木地板】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是木地板】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="11">窗帘<i>（第52天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（窗帘）中的开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是窗帘】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>核尺时间 </td>
			<td>D</td>
			<td>项目经理提报复尺单，类别为【窗帘】的创建时间</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是窗帘】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>F</td>
			<td>biz_order_install_plan中【安装项是窗帘】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>G</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>H</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是窗帘】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>J</td>
			<td>biz_order_install_plan中【安装项是窗帘】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>K</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="9">竣工验收<i>（第60天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+约检节点（竣工验收 ）中的开工后第几天申请</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是竣工验收】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望验收日期</td>
			<td>D</td>
			<td>biz_qc_bill【约检单】项目经理申请的【节点是竣工验收】的【期望上门日期】</td>
		</tr>
		<tr>
			<td>质检上门日期</td>
			<td>E</td>
			<td>约检单中节点为【竣工验收】的签到时间</td>
		</tr>
		<tr>
			<td>上门延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划验收日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>H</td>
			<td>biz_qc_bill【约检单】且【状态是已质检确认】且【节点是竣工验收】的验收日期accept_check_datetime</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>I</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="3">尾款<i>（第62天）</i></td>
			<td>计划</td>
			<td>A</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际</td>
			<td>B</td>
			<td>客户实际收交二期款的日期来源，数据来源biz_pre_pm_settle_finance_receive_moeny表中</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>C</td>
			<td>receive_money_type为2的交款时间receive_money_datetime</td>
		</tr>
		</tbody>
		<tbody class="bg_f1">
		<tr>
			<td rowspan="10">家电<i>（第69天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（家电安装）中的实际开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是家电】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是家电】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是家电】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是家电】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是家电】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>C-A</td>
		</tr>
		</tbody>
		<tbody>
		<tr>
			<td rowspan="10">家具<i>（第69天）</i></td>
			<td>计划提报时间</td>
			<td>A</td>
			<td>实际开工日期+主材安装节点（家具安装）中的实际开工后第几天申请安装</td>
		</tr>
		<tr>
			<td>实际提报时间</td>
			<td>B</td>
			<td>biz_order_install_plan中【安装项是家具】的【提交时间时分秒】</td>
		</tr>
		<tr>
			<td>提报延期天数</td>
			<td>C</td>
			<td>B-A</td>
		</tr>
		<tr>
			<td>期望进场日期</td>
			<td>D</td>
			<td>biz_order_install_plan中【安装项是家具】的【申请进场日期】</td>
		</tr>
		<tr>
			<td>实际进场时间</td>
			<td>E</td>
			<td>biz_order_install_plan中【安装项是家具】的【实际进场日期】</td>
		</tr>
		<tr>
			<td>进场延期天数</td>
			<td>F</td>
			<td>E-D</td>
		</tr>
		<tr>
			<td>计划完成日期</td>
			<td>G</td>
			<td>biz_node_plan中的计划完成日期plan_done_date</td>
		</tr>
		<tr>
			<td>实际完成时间</td>
			<td>H</td>
			<td>biz_order_install_plan中【安装项是家具】的【实际完工日期】</td>
		</tr>
		<tr>
			<td>实际验收合格时间</td>
			<td>I</td>
			<td>biz_order_install_plan中【安装项是家具】的【实际验收日期】</td>
		</tr>
		<tr>
			<td>正常/延期/提前天数</td>
			<td>J</td>
			<td>C-A</td>
		</tr>
		</tbody>
	</table>
	<div class="btn"><a href="#" onclick="history.go(-1)">返回</a></div>
</div>
</body>
</html>